package com.example.donutflipscanner.market.risk;

public enum MarketAnomalyType {
    EXTREME_HIGH_SALES,
    EXTREME_LOW_SALES,
    SUDDEN_PRICE_JUMP,
    SUDDEN_PRICE_DROP,
    SELLER_CONCENTRATION,
    BUYER_CONCENTRATION,
    REPEATED_IDENTICAL_UNUSUAL_TRADES,
    RAPID_ALTERNATING_TRANSACTIONS,
    LOW_VOLUME_PRICE_SPIKE,
    ACTIVE_ASKS_FAR_ABOVE_SALES,
    ACTIVE_ASKS_FAR_BELOW_SALES,
    NEW_CUSTOM_ITEM_VARIANT,
    MISSING_VALUE_METADATA,
    CIRCULAR_TRADING_PATTERN
}
