package com.example.donutflipscanner.market.item.model;

public enum ItemNormalizationIssue {
    MISSING_ITEM_ID,
    INVALID_ITEM_ID,
    MISSING_STACK_COUNT,
    INVALID_STACK_COUNT,
    INVALID_ENCHANTMENT,
    INCOMPLETE_ARMOR_TRIM,
    UNKNOWN_API_METADATA,
    DAMAGE_METADATA_UNAVAILABLE,
    VALUE_METADATA_UNAVAILABLE,
    DURABILITY_NOT_EXPOSED,
    VISIBLE_METADATA_ONLY,
    FILLED_CONTAINER_CAUTION,
    UNEXPECTED_CONTAINER_CONTENTS,
    CONTAINER_DEPTH_EXCEEDED,
    CONTAINER_ENTRY_LIMIT_EXCEEDED,
    CATEGORY_NOT_EXPLICITLY_SAFE,
    SERVER_SPECIFIC_ITEM
}
