package com.example.donutflipscanner.market.opportunity;

public enum OpportunityRejectionCode {
    INVALID_LISTING,
    LISTING_EXPIRED,
    LISTING_NOT_ACTIVE,
    ITEM_NOT_WHITELISTED,
    ITEM_BLACKLISTED,
    ITEM_PROFILE_DISABLED,
    ITEM_MATCH_UNSUPPORTED,
    SEVERE_MARKET_RISK,
    FAIR_VALUE_UNAVAILABLE,
    PROFIT_REQUIREMENT_FAILED,
    CONFIDENCE_BELOW_MINIMUM,
    COMPARABLE_SALES_BELOW_MINIMUM
}
