package com.example.donutflipscanner.market.profit;

public enum ProfitRejectionCode {
    FAIR_VALUE_UNAVAILABLE,
    PURCHASE_PRICE_NOT_POSITIVE,
    GROSS_PROFIT_BELOW_MINIMUM,
    NET_PROFIT_BELOW_MINIMUM,
    ROI_UNAVAILABLE,
    ROI_BELOW_MINIMUM,
    GLOBAL_MAXIMUM_PURCHASE_PRICE_EXCEEDED,
    ITEM_MAXIMUM_PURCHASE_PRICE_EXCEEDED,
    BANKROLL_PERCENTAGE_LIMIT_EXCEEDED,
    OPEN_EXPOSURE_LIMIT_EXCEEDED
}
